* SDL2 as a Library

LITE would like to thank the developers of SDL2 for releasing free and
open source software for everybody in the world to use, without worry.

** Dependencies

NOTE: The /DEVELOPMENT/ releases are necessary (don't get runtime binaries).

- [[https://www.libsdl.org/download-2.0.php][SDL2]]
- [[https://github.com/libsdl-org/SDL_ttf/releases/latest][SDL2_ttf]]

On most Linux distros: ~sudo apt install libsdl2-dev libsdl2-ttf-dev~

** Notes

*** Version

This library has been successfully built for Windows and Linux using
SDL2 ~2.0.22~ with both of SDL2_ttf ~2.0.18~ and ~2.20.0~.

*** Working Directory

Currently, it is important to start LITE with a working directory of the base
of the repository or a subdirectory so that fonts may be properly found.

In the future, we hope to provide better methods of handling fonts.

*** Windows

- Specify SDL2

  Specify SDL2_DIR CMake variable during configuration.
  : -DSDL2_DIR=<full path to SDL2 directory containing bin, lib, include>

  It is also necessary to set SDL2_TTF_DIR CMake variable to find SDL_TTF extension.
  : -DSDL2_TTF_DIR=<full path to SDL2_ttf directory containing bin, lib, include>

- Missing DLLs/DLL error messages

  If the program compiles and links with zero errors, but exits immediately
  upon launching the executable, it is likely that the necessary DLLs, ~SDL2.dll~
  and ~SDL2_ttf.dll~, are not located in the same folder as the executable.

  The DLLs can be found in the ~lib~ subdirectory of the SDL
  development binaries, linked above.

  If you get errors about undefined entry points to specific functions,
  it's likely that the included SDL2 DLL(s) do not match your system's
  installed version. To remedy this, copy the DLL(s) from the local
  SDL2 installs into the same directory as the LITE executable; the
  ones you gave a path to after ~SDL2_DIR~ and ~SDL2_TTF_DIR~. It will
  be under ~bin~ if you use MinGW, or ~lib~ for VC.

  Currently, SDL2 2.0.22 and SDL2_ttf 2.20.0 DLLs are included.

- Debug Output

  On Windows, when launching LITE GFX compiled with a toolchain,
  it launches with no console, and no output when launched from a
  terminal. Because of this, it is necessary to use IO redirection if
  you wish to see ~printf()~ output, and you can only see it once the
  program has exited entirely.

  Nushell:
  : bin/LITE | save bin/log.txt ; cat bin/log.txt

  Bash:
  : bin/LITE > bin/log.txt 2>&1 && cat bin/log.txt

  PowerShell:
  : .\bin\LITE | Out-File .\bin\log.txt ; Get-Contents -Path .\bin\log.txt
