* SDL2 as a Library

** Dependencies

NOTE: The /DEVELOPMENT/ releases are necessary (don't get runtime binaries).

- [[https://www.libsdl.org/download-2.0.php][SDL2]]
- [[https://github.com/libsdl-org/SDL_ttf/releases/latest][SDL2_ttf]]

On most Linux distros: ~sudo apt install libsdl2-dev libsdl2-ttf-dev~

** Notes

*** Working Directory

Currently, it is important to start LITE with a working directory of the base
of the repository or a subdirectory so that fonts may be properly found. \\
In the future, we hope to provide better methods of handling fonts.

*** Windows

- Specify SDL2

  Specify SDL2_DIR CMake variable during configuration.
  : -DSDL2_DIR=<full path to SDL2 directory containing bin, lib, include>

  It is also necessary to set SDL2_TTF_DIR CMake variable to find SDL_TTF extension.
  : -DSDL2_TTF_DIR=<full path to SDL2_ttf directory containing bin, lib, include>

- Missing DLLs

  If the program compiles and links with zero errors, but exits immediately
  upon launching the executable, it is likely that the necessary DLLs, ~SDL2.dll~
  and ~SDL2_ttf.dll~, are not located in the same folder as the executable.

- Debug Output

  Because graphical applications exit immediately (at least on Windows),
  it is necessary to use IO redirection if you wish to see ~printf()~ output.

  Nushell:
  : bin/LITE | save bin/log.txt ; cat bin/log.txt

  Bash:
  : bin/LITE > bin/log.txt 2>&1 && cat bin/log.txt

  PowerShell:
  : .\bin\LITE | Out-File .\bin\log.txt ; Get-Contents -Path .\bin\log.txt
